<a href="https://colab.research.google.com/github/crystalclcm/Dissertation-Crystal-Matticks/blob/main/University_skills.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing and Scraping Universities - DCU, TCD, UG, UL, TUD

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.dcu.ie/courses/undergraduate/business-school/accounting-and-finance#prospectus-structure"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

# Example: Extract overview
overview_section = soup.find("div", {"class": "field--name-body"})
if overview_section:
    text = overview_section.get_text(separator=" ", strip=True)
    data.append(["DCU", "Accounting & Finance", "Overview", text, url])

# Example: Extract modules
modules = soup.find_all("div", {"class": "module"})
for m in modules:
    module_name = m.find("h3").get_text(strip=True) if m.find("h3") else ""
    module_desc = m.get_text(separator=" ", strip=True)
    data.append(["DCU", "Accounting & Finance", module_name, module_desc, url])

df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("dcu_accounting.csv", index=False)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.tcd.ie/scss/courses/undergraduate/computer-science/course-structure/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["TCD", "Computer Science", section, text, url])

# 1. Extract overview
overview = soup.find("div", {"class": "field--name-body"})
if overview:
    text = overview.get_text(separator=" ", strip=True)
    add_row("Overview", text)

# 2. Extract module sections (headers + following text)
headers = soup.find_all(["h3", "h4"])
for h in headers:
    module_name = h.get_text(strip=True)
    desc_block = h.find_next_sibling("div")
    if desc_block:
        desc_text = desc_block.get_text(separator=" ", strip=True)
        add_row(f"Module: {module_name}", desc_text)

# 3. Extract expandable <details> sections
details_blocks = soup.find_all("details")
for block in details_blocks:
    summary = block.find("summary")
    if summary:
        section_name = summary.get_text(strip=True)
        content = block.get_text(separator=" ", strip=True)
        add_row(f"Expandable: {section_name}", content)

# 4. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("tcd_computer_science.csv", index=False)

print("Saved: tcd_computer_science.csv")

Saved: tcd_computer_science.csv

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.ul.ie/courses/bachelor-business-studies#modules"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["UL", "Business Studies", section, text, url])

# 1. Extract module blocks
modules = soup.find_all("div", {"class": "module-item"})

for m in modules:
    # Module title
    title = m.find("h3")
    module_name = title.get_text(strip=True) if title else "Unknown Module"

    # Module description
    desc = m.find("div", {"class": "module-description"})
    desc_text = desc.get_text(separator=" ", strip=True) if desc else ""

    add_row(f"Module: {module_name}", desc_text)

    # Learning outcomes (if present)
    lo = m.find("div", {"class": "learning-outcomes"})
    if lo:
        lo_text = lo.get_text(separator=" ", strip=True)
        add_row(f"Learning Outcomes: {module_name}", lo_text)

# 2. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("ul_business.csv", index=False)

print("Saved: ul_business.csv")

Saved: ul_business.csv

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.tudublin.ie/study/undergraduate/courses/accounting-tu670/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["TU Dublin", "Accounting", section, text, url])

# 1. Extract overview (usually in a main content div)
overview = soup.find("div", {"class": "course-introduction"})
if overview:
    text = overview.get_text(separator=" ", strip=True)
    add_row("Overview", text)

# 2. Extract accordion sections (Course Content, What You Will Study, etc.)
accordion_items = soup.find_all("div", {"class": "accordion-item"})
for item in accordion_items:
    header = item.find("h3")
    content = item.find("div", {"class": "accordion-content"})

    if header and content:
        section_name = header.get_text(strip=True)
        section_text = content.get_text(separator=" ", strip=True)
        add_row(section_name, section_text)

# 3. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("tud_accounting.csv", index=False)

print("Saved: tud_accounting.csv")

Saved: tud_accounting.csv

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.dcu.ie/courses/undergraduate/school-computing/computer-science"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["DCU", "Computer Science", section, text, url])

# 1. Extract overview
overview = soup.find("div", {"class": "field--name-body"})
if overview:
    text = overview.get_text(separator=" ", strip=True)
    add_row("Overview", text)

# 2. Extract module sections (headers + following text)
headers = soup.find_all(["h2", "h3", "h4"])
for h in headers:
    section_name = h.get_text(strip=True)

    # Find the next content block
    content = h.find_next_sibling("div")
    if content:
        section_text = content.get_text(separator=" ", strip=True)
        add_row(section_name, section_text)

# 3. Extract expandable sections (if present)
details_blocks = soup.find_all("details")
for block in details_blocks:
    summary = block.find("summary")
    if summary:
        section_name = summary.get_text(strip=True)
        content = block.get_text(separator=" ", strip=True)
        add_row(f"Expandable: {section_name}", content)

# 4. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("dcu_computer_science.csv", index=False)

print("Saved: dcu_computer_science.csv")

Saved: dcu_computer_science.csv

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.ul.ie/courses/bsc-computer-science"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["UL", "Computer Science", section, text, url])

# 1. Extract overview
overview = soup.find("div", {"class": "course-introduction"})
if overview:
    text = overview.get_text(separator=" ", strip=True)
    add_row("Overview", text)

# 2. Extract accordion sections (Course Content, What You Will Study, etc.)
accordion_items = soup.find_all("div", {"class": "accordion-item"})
for item in accordion_items:
    header = item.find("h3")
    content = item.find("div", {"class": "accordion-content"})

    if header and content:
        section_name = header.get_text(strip=True)
        section_text = content.get_text(separator=" ", strip=True)
        add_row(section_name, section_text)

# 3. Extract module blocks (UL sometimes lists modules separately)
modules = soup.find_all("div", {"class": "module-item"})
for m in modules:
    title = m.find("h3")
    module_name = title.get_text(strip=True) if title else "Unknown Module"

    desc = m.find("div", {"class": "module-description"})
    desc_text = desc.get_text(separator=" ", strip=True) if desc else ""

    add_row(f"Module: {module_name}", desc_text)

    lo = m.find("div", {"class": "learning-outcomes"})
    if lo:
        lo_text = lo.get_text(separator=" ", strip=True)
        add_row(f"Learning Outcomes: {module_name}", lo_text)

# 4. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("ul_computer_science.csv", index=False)

print("Saved: ul_computer_science.csv")

Saved: ul_computer_science.csv

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.tudublin.ie/study/undergraduate/courses/computing-tu856/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["TU Dublin", "Computer Science", section, text, url])

# 1. Extract overview
overview = soup.find("div", {"class": "course-introduction"})
if overview:
    text = overview.get_text(separator=" ", strip=True)
    add_row("Overview", text)

# 2. Extract accordion sections (Course Content, What You Will Study, etc.)
accordion_items = soup.find_all("div", {"class": "accordion-item"})
for item in accordion_items:
    header = item.find("h3")
    content = item.find("div", {"class": "accordion-content"})

    if header and content:
        section_name = header.get_text(strip=True)
        section_text = content.get_text(separator=" ", strip=True)
        add_row(section_name, section_text)

# 3. Extract module blocks (if TU Dublin lists modules separately)
modules = soup.find_all("div", {"class": "module-item"})
for m in modules:
    title = m.find("h3")
    module_name = title.get_text(strip=True) if title else "Unknown Module"

    desc = m.find("div", {"class": "module-description"})
    desc_text = desc.get_text(separator=" ", strip=True) if desc else ""

    add_row(f"Module: {module_name}", desc_text)

# 4. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("tud_computer_science.csv", index=False)

print("Saved: tud_computer_science.csv")

Saved: tud_computer_science.csv

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.universityofgalway.ie/courses/undergraduate-courses/computer-science.html"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

data = []

def add_row(section, text):
    data.append(["Galway", "Computer Science", section, text, url])

# 1. Extract overview
overview = soup.find("div", {"class": "course-introduction"})
if overview:
    text = overview.get_text(separator=" ", strip=True)
    add_row("Overview", text)

# 2. Extract accordion sections (Course Outline, Why Choose This Course, etc.)
accordion_items = soup.find_all("div", {"class": "accordion-item"})
for item in accordion_items:
    header = item.find("h3")
    content = item.find("div", {"class": "accordion-content"})

    if header and content:
        section_name = header.get_text(strip=True)
        section_text = content.get_text(separator=" ", strip=True)
        add_row(section_name, section_text)

# 3. Extract module blocks (if listed)
modules = soup.find_all("div", {"class": "module-item"})
for m in modules:
    title = m.find("h3")
    module_name = title.get_text(strip=True) if title else "Unknown Module"

    desc = m.find("div", {"class": "module-description"})
    desc_text = desc.get_text(separator=" ", strip=True) if desc else ""

    add_row(f"Module: {module_name}", desc_text)

# 4. Save CSV
df = pd.DataFrame(data, columns=["university", "course", "section", "text", "url"])
df.to_csv("galway_computer_science.csv", index=False)

print("Saved: galway_computer_science.csv")

Saved: galway_computer_science.csv

In [9]:
!pip install pdfplumber
import pdfplumber

pdf_path = "/content/BESS_Handbook_202526_V2 (1).pdf"

text = ""
with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        text += page.extract_text() + "\n"

print("PDF loaded. Total characters:", len(text))

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.6.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
PDF loaded. Total characters: 224660

In [10]:
import re

accounting_sections = []

# Split by module headings (Trinity uses "Module Code" or similar patterns)
chunks = re.split(r"(Module\s+Code:|MODULE\s+CODE:)", text)

for chunk in chunks:
    if any(keyword.lower() in chunk.lower() for keyword in [
        "accounting",
        "financial",
        "audit",
        "tax",
        "corporate finance",
        "management accounting"
    ]):
        accounting_sections.append(chunk)

len(accounting_sections)

1

In [11]:
accounting_text = accounting_sections[0]

import re

# Look for all learning outcomes sections inside the block
matches = re.findall(
    r"(Learning Outcomes|LEARNING OUTCOMES)([\s\S]*?)(Assessment|ASSESSMENT|Module Content|MODULE CONTENT)",
    accounting_text
)

len(matches)

10

In [12]:
learning_outcomes = [m[1].strip() for m in matches]

import pandas as pd

df = pd.DataFrame({
    "module_name": [f"Accounting Module {i+1}" for i in range(len(learning_outcomes))],
    "learning_outcomes": learning_outcomes
})

df.head()

           module_name                                  learning_outcomes
0  Accounting Module 1  .................................................
1  Accounting Module 2  Having successfully completed this programme s...
2  Accounting Module 3  IRU1144Y Ceart agus Labhairt na Teanga: Having...
3  Accounting Module 4  : On successful completion of both modules, st...
4  Accounting Module 5  On successful completion of this module, stude...

In [13]:
df.to_csv("tcd_accounting_from_bess.csv", index=False)
print("Saved tcd_accounting_from_bess.csv")

Saved tcd_accounting_from_bess.csv

In [48]:
#rescraping
import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrape_programme(url, university, programme):
    try:
        r = requests.get(url, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")

        # Extract all readable text from main content areas
        # This works across UL, TU Dublin, Galway, DCU, TCD
        selectors = [
            "main",
            "article",
            ".content",
            ".region-content",
            ".page-content",
            "#content",
            ".node__content"
        ]

        text_blocks = []
        for sel in selectors:
            for block in soup.select(sel):
                text_blocks.append(block.get_text(separator=" ", strip=True))

        # Fallback: whole page text
        if not text_blocks:
            text_blocks = [soup.get_text(separator=" ", strip=True)]

        # Clean
        text = " ".join(text_blocks)
        text = " ".join(text.split())

        return {
            "university": university,
            "programme": programme,
            "url": url,
            "text": text
        }

    except Exception as e:
        return {
            "university": university,
            "programme": programme,
            "url": url,
            "text": f"ERROR: {e}"
        }

# ---- Add your programme URLs here ----

programmes = [
    # UL
    ("UL", "Accounting", "https://www.ul.ie/courses/bachelor-business-studies#about-course"),
    ("UL", "Computer Science", "https://www.ul.ie/courses/computer-science-common-entry?utm_source=google&utm_medium=cpc&utm_campaign=cp_ul_ug_fy26_recruitment_search&utm_stage=conversion&utm_objective=conversions&utm_content=computer&utm_format=search&utm_lang=en&utm_term=keyword_computer&utm_id=cp_ul_ug_fy26_recruitment_search_conversion_conversions&gad_source=1&gad_campaignid=22952131888&gbraid=0AAAABA2kFBVFlRV6hulLRdoLzYP2dM8HV&gclid=CjwKCAjw1tLOBhAMEiwAiPkRHrt4I-E7unZ-obOnngNDgyzc_K2oew5Yl24JqSA0I0j2swnKO1H8YhoCml8QAvD_BwE"),

    # TU Dublin
    ("TU Dublin", "Accounting", "https://www.tudublin.ie/study/undergraduate/courses/accounting-tu910/"),
    ("TU Dublin", "Computer Science", "https://www.tudublin.ie/study/undergraduate/courses/computer-science-tu856/"),

    # Galway
    ("Galway", "Computer Science", "https://www.universityofgalway.ie/courses/undergraduate-courses/computer-science.html"),
]


# ---- Run scraper ----

rows = []
for uni, prog, url in programmes:
    print(f"Scraping {uni} – {prog}")
    rows.append(scrape_programme(url, uni, prog))

df = pd.DataFrame(rows)
df.head()

Scraping UL – Accounting
Scraping UL – Computer Science
Scraping TU Dublin – Accounting
Scraping TU Dublin – Computer Science
Scraping Galway – Computer Science

,university,programme,url,text
0,UL,Accounting,https://www.ul.ie/courses/bachelor-business-st...,Bachelor of Business Studies Breadcrumbs UL Ho...
1,UL,Computer Science,https://www.ul.ie/courses/computer-science-com...,Computer Science Common Entry Breadcrumbs UL H...
2,TU Dublin,Accounting,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Accounting (T...
3,TU Dublin,Computer Science,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Computer Scie...
4,Galway,Computer Science,https://www.universityofgalway.ie/courses/unde...,Courses Undergraduate Courses Postgraduate Tau...

# Cleaning

In [49]:
import re

def clean_text(t):
    t = re.sub(r"Breadcrumbs.*?UL Home", "", t, flags=re.IGNORECASE)
    t = re.sub(r"Home Study Undergraduate Courses", "", t, flags=re.IGNORECASE)
    t = re.sub(r"Courses Undergraduate Courses Postgraduate.*?Courses", "", t, flags=re.IGNORECASE)
    t = re.sub(r"\s+", " ", t)
    return t.strip()

df["clean_text"] = df["text"].apply(clean_text)
df[["university", "programme", "clean_text"]].head()

,university,programme,clean_text
0,UL,Accounting,Bachelor of Business Studies Courses Key infor...
1,UL,Computer Science,Computer Science Common Entry Courses Key info...
2,TU Dublin,Accounting,Accounting (TU910) Accounting Cuntasaíocht ┐Ai...
3,TU Dublin,Computer Science,Computer Science (TU856) Computer Science Ríom...
4,Galway,Computer Science,"Professional, Part-time and Evening Courses Ph..."

In [60]:
df_programmes = df.copy()
df_programmes["module"] = df_programmes["programme"]
df_programmes = df_programmes[["university", "programme", "module", "url", "text"]]
df_programmes.head()

,university,programme,module,url,text
0,UL,Accounting,Accounting,https://www.ul.ie/courses/bachelor-business-st...,Bachelor of Business Studies Breadcrumbs UL Ho...
1,UL,Computer Science,Computer Science,https://www.ul.ie/courses/computer-science-com...,Computer Science Common Entry Breadcrumbs UL H...
2,TU Dublin,Accounting,Accounting,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Accounting (T...
3,TU Dublin,Computer Science,Computer Science,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Computer Scie...
4,Galway,Computer Science,Computer Science,https://www.universityofgalway.ie/courses/unde...,Courses Undergraduate Courses Postgraduate Tau...

In [51]:
import pandas as pd
import glob

module_files = [
    "tcd_computer_science.csv",
    "dcu_computer_science.csv",
    "dcu_accounting.csv",
    "tcd_accounting_from_bess.csv"
]

dfs = []
for f in module_files:
    df = pd.read_csv(f)
    df["source_file"] = f
    dfs.append(df)

df_modules = pd.concat(dfs, ignore_index=True)
df_modules.head()

,university,course,section,text,url,source_file,module_name,learning_outcomes
0,TCD,Computer Science,Module: Flexibility,The first three years of the programme are the...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
1,TCD,Computer Science,Module: Industry Internships,In their fourth year Master in Computer Scienc...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
2,TCD,Computer Science,Module: First Year,Mathematics Computer Programming Microprocesso...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
3,TCD,Computer Science,Module: Second Year,Discrete Mathematics Algorithms & Data Structu...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
4,TCD,Computer Science,Module: Third Year,Symbolic Programming Introduction to Functiona...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN

In [52]:
# Handle Trinity BESS separately
bess = df_modules[df_modules["source_file"] == "tcd_accounting_from_bess.csv"].copy()
bess = bess.rename(columns={"module_name": "module", "learning_outcomes": "text"})
bess["university"] = "Trinity"
bess["programme"] = "Accounting"
bess["url"] = ""

# Handle the others
others = df_modules[df_modules["source_file"] != "tcd_accounting_from_bess.csv"].copy()

others["text"] = others["text"].fillna("").astype(str)
others["module"] = (others["course"].fillna("") + " " + others["section"].fillna("")).str.strip()

def detect_programme(f):
    f = f.lower()
    if "account" in f:
        return "Accounting"
    if "business" in f:
        return "Business"
    return "Computer Science"

others["programme"] = others["source_file"].apply(detect_programme)

others = others[["university", "programme", "module", "url", "text"]]
bess = bess[["university", "programme", "module", "url", "text"]]

In [58]:
rows = []
for uni, prog, url in programmes:
    rows.append(scrape_programme(url, uni, prog))

df = pd.DataFrame(rows)

In [59]:
df.columns
df.head()

,university,programme,url,text
0,UL,Accounting,https://www.ul.ie/courses/bachelor-business-st...,Bachelor of Business Studies Breadcrumbs UL Ho...
1,UL,Computer Science,https://www.ul.ie/courses/computer-science-com...,Computer Science Common Entry Breadcrumbs UL H...
2,TU Dublin,Accounting,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Accounting (T...
3,TU Dublin,Computer Science,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Computer Scie...
4,Galway,Computer Science,https://www.universityofgalway.ie/courses/unde...,Courses Undergraduate Courses Postgraduate Tau...

In [62]:
import pandas as pd

module_files = [
    "tcd_computer_science.csv",
    "dcu_computer_science.csv",
    "dcu_accounting.csv",
    "tcd_accounting_from_bess.csv"
]

dfs = []
for f in module_files:
    df_temp = pd.read_csv(f)
    df_temp["source_file"] = f
    dfs.append(df_temp)

df_modules = pd.concat(dfs, ignore_index=True)
df_modules.head(20)

,university,course,section,text,url,source_file,module_name,learning_outcomes
0,TCD,Computer Science,Module: Flexibility,The first three years of the programme are the...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
1,TCD,Computer Science,Module: Industry Internships,In their fourth year Master in Computer Scienc...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
2,TCD,Computer Science,Module: First Year,Mathematics Computer Programming Microprocesso...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
3,TCD,Computer Science,Module: Second Year,Discrete Mathematics Algorithms & Data Structu...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
4,TCD,Computer Science,Module: Third Year,Symbolic Programming Introduction to Functiona...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
5,TCD,Computer Science,Module: Fourth Year : BA (Mod) Computer Science,Human Factors Technology Entrepreneurship Four...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
6,TCD,Computer Science,Module: Fourth Year: Master in Computer Science,Human Factors Technology Entrepreneurship Four...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
7,TCD,Computer Science,Module: Fifth Year: Master in Computer Science,Research Methods Four or five of the following...,https://www.tcd.ie/scss/courses/undergraduate/...,tcd_computer_science.csv,NaN,NaN
8,DCU,Computer Science,Overview,Assistive Tools | Loop | Staff | Library | Vac...,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
9,DCU,Computer Science,Course Details,CAO Code: DC121 Course Type: Undergraduate NFQ...,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
10,DCU,Computer Science,Overview,NaN,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
11,DCU,Computer Science,Why DCU,DCU is ranked No 1 in Ireland for Graduate Emp...,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
12,DCU,Computer Science,DCU is ranked No 1 in Ireland for Graduate Emp...,QS Graduate Employability Rankings 2022,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
13,DCU,Computer Science,DCU is ranked 19th globally for Graduate Emplo...,QS Graduate Employability Rankings 2022,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
14,DCU,Computer Science,91% of graduates are in employment or further ...,Graduate Outcomes Survey,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
15,DCU,Computer Science,DCU People,Luke Derwin Alumni Luke Derwin’s interest in c...,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
16,DCU,Computer Science,Careers & Further Options,NaN,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
17,DCU,Computer Science,Careers,Some Computer Applications (Computer Science) ...,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
18,DCU,Computer Science,Entry Requirements,NaN,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN
19,DCU,Computer Science,Course Structure,NaN,https://www.dcu.ie/courses/undergraduate/schoo...,dcu_computer_science.csv,NaN,NaN

In [63]:
bess = df_modules[df_modules["source_file"] == "tcd_accounting_from_bess.csv"].copy()
bess = bess.rename(columns={"module_name": "module", "learning_outcomes": "text"})
bess["university"] = "Trinity"
bess["programme"] = "Accounting"
bess["url"] = ""
bess = bess[["university", "programme", "module", "url", "text"]]

In [64]:
others = df_modules[df_modules["source_file"] != "tcd_accounting_from_bess.csv"].copy()

others["text"] = others["text"].fillna("").astype(str)
others["module"] = (others["course"].fillna("") + " " + others["section"].fillna("")).str.strip()

def detect_programme(f):
    f = f.lower()
    if "account" in f:
        return "Accounting"
    if "business" in f:
        return "Business"
    return "Computer Science"

others["programme"] = others["source_file"].apply(detect_programme)

others = others[["university", "programme", "module", "url", "text"]]

In [66]:
print("PROGRAMMES:", df_programmes.columns.tolist())
print("OTHERS:", others.columns.tolist())
print("BESS:", bess.columns.tolist())

PROGRAMMES: ['university', 'programme', 'module', 'url', 'text']
OTHERS: ['university', 'programme', 'module', 'url', 'text']
BESS: ['university', 'programme', 'module', 'url', 'text', 'text']

In [67]:
# Fix duplicate 'text' columns in bess
bess = bess.loc[:, ~bess.columns.duplicated()]  # removes duplicate column names

In [68]:
bess = bess[["university", "programme", "module", "url", "text"]]

In [70]:
clean_all = pd.concat([df_programmes, others, bess], ignore_index=True)
clean_all = clean_all.drop_duplicates().reset_index(drop=True)
clean_all.head(20)

,university,programme,module,url,text
0,UL,Accounting,Accounting,https://www.ul.ie/courses/bachelor-business-st...,Bachelor of Business Studies Breadcrumbs UL Ho...
1,UL,Computer Science,Computer Science,https://www.ul.ie/courses/computer-science-com...,Computer Science Common Entry Breadcrumbs UL H...
2,TU Dublin,Accounting,Accounting,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Accounting (T...
3,TU Dublin,Computer Science,Computer Science,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Computer Scie...
4,Galway,Computer Science,Computer Science,https://www.universityofgalway.ie/courses/unde...,Courses Undergraduate Courses Postgraduate Tau...
5,TCD,Computer Science,Computer Science Module: Flexibility,https://www.tcd.ie/scss/courses/undergraduate/...,The first three years of the programme are the...
6,TCD,Computer Science,Computer Science Module: Industry Internships,https://www.tcd.ie/scss/courses/undergraduate/...,In their fourth year Master in Computer Scienc...
7,TCD,Computer Science,Computer Science Module: First Year,https://www.tcd.ie/scss/courses/undergraduate/...,Mathematics Computer Programming Microprocesso...
8,TCD,Computer Science,Computer Science Module: Second Year,https://www.tcd.ie/scss/courses/undergraduate/...,Discrete Mathematics Algorithms & Data Structu...
9,TCD,Computer Science,Computer Science Module: Third Year,https://www.tcd.ie/scss/courses/undergraduate/...,Symbolic Programming Introduction to Functiona...
10,TCD,Computer Science,Computer Science Module: Fourth Year : BA (Mod...,https://www.tcd.ie/scss/courses/undergraduate/...,Human Factors Technology Entrepreneurship Four...
11,TCD,Computer Science,Computer Science Module: Fourth Year: Master i...,https://www.tcd.ie/scss/courses/undergraduate/...,Human Factors Technology Entrepreneurship Four...
12,TCD,Computer Science,Computer Science Module: Fifth Year: Master in...,https://www.tcd.ie/scss/courses/undergraduate/...,Research Methods Four or five of the following...
13,DCU,Computer Science,Computer Science Overview,https://www.dcu.ie/courses/undergraduate/schoo...,Assistive Tools | Loop | Staff | Library | Vac...
14,DCU,Computer Science,Computer Science Course Details,https://www.dcu.ie/courses/undergraduate/schoo...,CAO Code: DC121 Course Type: Undergraduate NFQ...
15,DCU,Computer Science,Computer Science Overview,https://www.dcu.ie/courses/undergraduate/schoo...,
16,DCU,Computer Science,Computer Science Why DCU,https://www.dcu.ie/courses/undergraduate/schoo...,DCU is ranked No 1 in Ireland for Graduate Emp...
17,DCU,Computer Science,Computer Science DCU is ranked No 1 in Ireland...,https://www.dcu.ie/courses/undergraduate/schoo...,QS Graduate Employability Rankings 2022
18,DCU,Computer Science,Computer Science DCU is ranked 19th globally f...,https://www.dcu.ie/courses/undergraduate/schoo...,QS Graduate Employability Rankings 2022
19,DCU,Computer Science,Computer Science 91% of graduates are in emplo...,https://www.dcu.ie/courses/undergraduate/schoo...,Graduate Outcomes Survey

In [71]:
clean_all.columns

Index(['university', 'programme', 'module', 'url', 'text'], dtype='object')

In [72]:
clean_all["university"].value_counts()
clean_all["programme"].value_counts()
clean_all.head(10)

,university,programme,module,url,text
0,UL,Accounting,Accounting,https://www.ul.ie/courses/bachelor-business-st...,Bachelor of Business Studies Breadcrumbs UL Ho...
1,UL,Computer Science,Computer Science,https://www.ul.ie/courses/computer-science-com...,Computer Science Common Entry Breadcrumbs UL H...
2,TU Dublin,Accounting,Accounting,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Accounting (T...
3,TU Dublin,Computer Science,Computer Science,https://www.tudublin.ie/study/undergraduate/co...,Home Study Undergraduate Courses Computer Scie...
4,Galway,Computer Science,Computer Science,https://www.universityofgalway.ie/courses/unde...,Courses Undergraduate Courses Postgraduate Tau...
5,TCD,Computer Science,Computer Science Module: Flexibility,https://www.tcd.ie/scss/courses/undergraduate/...,The first three years of the programme are the...
6,TCD,Computer Science,Computer Science Module: Industry Internships,https://www.tcd.ie/scss/courses/undergraduate/...,In their fourth year Master in Computer Scienc...
7,TCD,Computer Science,Computer Science Module: First Year,https://www.tcd.ie/scss/courses/undergraduate/...,Mathematics Computer Programming Microprocesso...
8,TCD,Computer Science,Computer Science Module: Second Year,https://www.tcd.ie/scss/courses/undergraduate/...,Discrete Mathematics Algorithms & Data Structu...
9,TCD,Computer Science,Computer Science Module: Third Year,https://www.tcd.ie/scss/courses/undergraduate/...,Symbolic Programming Introduction to Functiona...

# Deep cleaning for ESCO extraction

In [73]:
import re

def deep_clean_text(t):
    # remove navigation and repeated site structure
    t = re.sub(r"Breadcrumbs.*?Home", "", t, flags=re.IGNORECASE)
    t = re.sub(r"Home Study Undergraduate Courses", "", t, flags=re.IGNORECASE)
    t = re.sub(r"Courses Undergraduate Courses Postgraduate.*?Courses", "", t, flags=re.IGNORECASE)
    t = re.sub(r"Apply Now|Entry Requirements|Fees|Contact Us", "", t, flags=re.IGNORECASE)
    t = re.sub(r"\s+", " ", t)
    return t.strip()

clean_all["text"] = clean_all["text"].astype(str).apply(deep_clean_text)
clean_all = clean_all[clean_all["text"].str.len() > 100]
clean_all.head(10)

,university,programme,module,url,text
0,UL,Accounting,Accounting,https://www.ul.ie/courses/bachelor-business-st...,Bachelor of Business Studies Courses Key infor...
1,UL,Computer Science,Computer Science,https://www.ul.ie/courses/computer-science-com...,Computer Science Common Entry Courses Key info...
2,TU Dublin,Accounting,Accounting,https://www.tudublin.ie/study/undergraduate/co...,Accounting (TU910) Accounting Cuntasaíocht ┐Ai...
3,TU Dublin,Computer Science,Computer Science,https://www.tudublin.ie/study/undergraduate/co...,Computer Science (TU856) Computer Science Ríom...
4,Galway,Computer Science,Computer Science,https://www.universityofgalway.ie/courses/unde...,"Professional, Part-time and Evening Courses Ph..."
5,TCD,Computer Science,Computer Science Module: Flexibility,https://www.tcd.ie/scss/courses/undergraduate/...,The first three years of the programme are the...
6,TCD,Computer Science,Computer Science Module: Industry Internships,https://www.tcd.ie/scss/courses/undergraduate/...,In their fourth year Master in Computer Scienc...
7,TCD,Computer Science,Computer Science Module: First Year,https://www.tcd.ie/scss/courses/undergraduate/...,Mathematics Computer Programming Microprocesso...
8,TCD,Computer Science,Computer Science Module: Second Year,https://www.tcd.ie/scss/courses/undergraduate/...,Discrete Mathematics Algorithms & Data Structu...
9,TCD,Computer Science,Computer Science Module: Third Year,https://www.tcd.ie/scss/courses/undergraduate/...,Symbolic Programming Introduction to Functiona...